apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api
  labels:
    app: demo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-api
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      containers:
      - name: app-container
        image: {{ .Values.image }}
        resources:
          limits:
            memory: "256Mi"
            cpu: "250m"
          requests:
            memory: "100Mi"
            cpu: "100m"
        ports:
        - containerPort: 80